function [fitresult] = createFit_SA_E(Strain_SA_E, Stress_SA_E)
%CREATEFIT(STRAIN_SA_E,STRESS_SA_E)
%  Create a fit.
%
%  Data for 'SA_E' fit:
%      X Input : Strain_SA_E
%      Y Output: Stress_SA_E
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 29-Jun-2018 14:40:08


%% Fit: 'SA_E'.
[xData, yData] = prepareCurveData( Strain_SA_E, Stress_SA_E );

% Set up fittype and options.
ft = fittype( 'poly1' );
excludedPoints = (xData < 0) | (xData > 3e-06);
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );




