function [fitresult, gof] = createFit_SA_C(Strain_SA_C, Stress_SA_C)
%CREATEFIT(STRAIN_SA_C,STRESS_SA_C)
%  Create a fit.
%
%  Data for 'SA_C' fit:
%      X Input : Strain_SA_C
%      Y Output: Stress_SA_C
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 29-Jun-2018 15:08:54


%% Fit: 'SA_C'.
[xData, yData] = prepareCurveData( Strain_SA_C, Stress_SA_C );

% Set up fittype and options.
ft = fittype( 'poly1' );
excludedPoints = (xData < 3e-08) | (xData > 2.3e-07);
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'SA_C' );
h = plot( fitresult, xData, yData, excludedPoints );
legend( h, 'Stress_SA_C vs. Strain_SA_C', 'Excluded Stress_SA_C vs. Strain_SA_C', 'SA_C', 'Location', 'NorthEast' );
% Label axes
xlabel Strain_SA_C
ylabel Stress_SA_C
grid on


